### ISSUE TITLE
Corrección módulo 4.

### ISSUE THREAD

**Issue by LksR-dev** [Mmaxi1720/desafiom4#1]
Hola Maxi, cómo estás? Estuve viendo tu desafío y está genial. 

Me gusta la animación que aplicaste para el menú en mobile, funciona todo muy bien. El único detalle que vi, es que en mobile, el form__container en donde tenes tus redes rompe apenas la página dando un scroll para el costado. El motivo de esto es el left: 10px; Al sacarlo, si bien no queda centrado, el scroll desaparece. 

 Algo que puede servir es quizás sacarle la posición relativa al logo, agregarle un padding-top, y también sacarle la posición relativa al contenedor de las redes y agregarle un margin-top. También revisar algunas propiedades que quizás no están haciendo efecto.

 De todas maneras no creo que sea algo grave cómo para desaprobar el desafío, pero si estaría bueno que intentes el cambio. Yo lo apruebo, felicidades!!

 Saludos!

**Comment by Mmaxi1720** [comment]
Buenas Lucas!
Gracias por tomarte el tiempo para revisarlo!
Tenes razon, haciendo esos cambios mejora bastante el footer.
Muchas gracias por el feedback.
Saludos!
