### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by amunozdev** [Mmaxi1720/desafiom4#2]
Hola @Mmaxi1720 felicitaciones por tu trabajo!

El titulo "Hola soy Maxi" esta descentrado horizontalmente, capaz que sacándole el left: 47%; quedaría mejor:
![Captura de pantalla de 2022-03-11 10-31-54](https://user-images.githubusercontent.com/77214476/157878172-9fec6867-3525-4f9b-8b1e-b5af69a5e1c9.png)

El formulario una vez enviado, estaría bueno que se limpien todos los campos

Más allá de esos detalles el desafío cumple con las condiciones de ser aprobado, éxitos en lo que sigue!

**Comment by Mmaxi1720** [comment]
Buenas @alexismunoz1 .
También, muchas gracias por tomarte el tiempo para ver el desafio.
Voy a tener en cuenta los puntos que me comentas para mejorarlos a futuro.
Graciass
